make a flag on the generate-password script to keep it alphanumeric

diff --git a/bin/generate-password b/bin/generate-password
--- a/bin/generate-password
+++ b/bin/generate-password
@@ -4,10 +4,34 @@
 #
 #   generate-password <num-chars>
 #
-# `num-chars` defaults to 40.
+# `num-chars` defaults to 40. You can also pass a `-a` flag to keep the password alphanumeric-only.
 
 set -euf -o pipefail
 
+# http://stackoverflow.com/a/16496491/358804
+usage() {
+  echo "Usage:\n\n  $0 [-a] [<num_chars>]\n" 1>&2
+  exit 1
+}
+
+BASE='a-zA-Z0-9!@#\$%^&\*\(\)\+=_'
+
+# http://wiki.bash-hackers.org/howto/getopts_tutorial#a_first_example
+while getopts ":a" opt; do
+  case $opt in
+    a)
+      # alphanumeric only
+      BASE='a-zA-Z0-9'
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      usage
+      ;;
+  esac
+done
+# http://wiki.bash-hackers.org/howto/getopts_tutorial#how_it_works
+shift $((OPTIND-1))
+
 NUM_CHARS=${1-40}
 # https://github.com/18F/cg-scripts/pull/18/files/1a38e626118bf4dfd622557128a2a829d275e5aa#r69313181
-cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9!@#\$%^&\*\(\)\+=_' | head -c $NUM_CHARS
+cat /dev/urandom | LC_ALL=C tr -dc $BASE | head -c $NUM_CHARS
